//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.0.30319.33440.
// 
namespace Cinteros.Crm.Utils.Shuffle.Types {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class importexportxml {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("entity", IsNullable=false)]
        public string[] entities;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("ribbon", IsNullable=false)]
        public string[] ribbons;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("dashboard", IsNullable=false)]
        public string[] dashboards;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("optionset", IsNullable=false)]
        public string[] optionsets;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("sitemap", IsNullable=false)]
        public string[] sitemaps;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("webresource", IsNullable=false)]
        public string[] webresources;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DataBlockImport {
        
        /// <remarks/>
        public DataBlockImportMatch Match;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool CreateWithId;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(SaveTypes.CreateUpdate)]
        public SaveTypes Save;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(DeleteTypes.None)]
        public DeleteTypes Delete;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool UpdateInactive;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool UpdateIdentical;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool Overwrite;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool OverwriteSpecified;
        
        public DataBlockImport() {
            this.CreateWithId = false;
            this.Save = SaveTypes.CreateUpdate;
            this.Delete = DeleteTypes.None;
            this.UpdateInactive = false;
            this.UpdateIdentical = false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class DataBlockImportMatch {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Attribute")]
        public DataBlockImportMatchAttribute[] Attribute;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool PreRetrieveAll;
        
        public DataBlockImportMatch() {
            this.PreRetrieveAll = false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class DataBlockImportMatchAttribute {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Name;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Display;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    public enum SaveTypes {
        
        /// <remarks/>
        CreateUpdate,
        
        /// <remarks/>
        CreateOnly,
        
        /// <remarks/>
        UpdateOnly,
        
        /// <remarks/>
        Never,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    public enum DeleteTypes {
        
        /// <remarks/>
        None,
        
        /// <remarks/>
        Existing,
        
        /// <remarks/>
        All,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DataBlockExport {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Filter")]
        public DataBlockExportFilter[] Filter;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Sort")]
        public DataBlockExportSort[] Sort;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Attribute", IsNullable=false)]
        public DataBlockExportAttribute[] Attributes;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool ActiveOnly;
        
        public DataBlockExport() {
            this.ActiveOnly = false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class DataBlockExportFilter {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Attribute;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public ConditionOperator Operator;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public FilterTypes Type;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TypeSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Value;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    public enum ConditionOperator {
        
        /// <remarks/>
        lt,
        
        /// <remarks/>
        Equal,
        
        /// <remarks/>
        NotEqual,
        
        /// <remarks/>
        GreaterThan,
        
        /// <remarks/>
        LessThan,
        
        /// <remarks/>
        GreaterEqual,
        
        /// <remarks/>
        LessEqual,
        
        /// <remarks/>
        Like,
        
        /// <remarks/>
        NotLike,
        
        /// <remarks/>
        In,
        
        /// <remarks/>
        NotIn,
        
        /// <remarks/>
        Between,
        
        /// <remarks/>
        NotBetween,
        
        /// <remarks/>
        Null,
        
        /// <remarks/>
        NotNull,
        
        /// <remarks/>
        Yesterday,
        
        /// <remarks/>
        Today,
        
        /// <remarks/>
        Tomorrow,
        
        /// <remarks/>
        Last7Days,
        
        /// <remarks/>
        Next7Days,
        
        /// <remarks/>
        LastWeek,
        
        /// <remarks/>
        ThisWeek,
        
        /// <remarks/>
        NextWeek,
        
        /// <remarks/>
        LastMonth,
        
        /// <remarks/>
        ThisMonth,
        
        /// <remarks/>
        NextMonth,
        
        /// <remarks/>
        On,
        
        /// <remarks/>
        OnOrBefore,
        
        /// <remarks/>
        OnOrAfter,
        
        /// <remarks/>
        LastYear,
        
        /// <remarks/>
        ThisYear,
        
        /// <remarks/>
        NextYear,
        
        /// <remarks/>
        LastXHours,
        
        /// <remarks/>
        NextXHours,
        
        /// <remarks/>
        LastXDays,
        
        /// <remarks/>
        NextXDays,
        
        /// <remarks/>
        LastXWeeks,
        
        /// <remarks/>
        NextXWeeks,
        
        /// <remarks/>
        LastXMonths,
        
        /// <remarks/>
        NextXMonths,
        
        /// <remarks/>
        LastXYears,
        
        /// <remarks/>
        NextXYears,
        
        /// <remarks/>
        EqualUserId,
        
        /// <remarks/>
        NotEqualUserId,
        
        /// <remarks/>
        EqualBusinessId,
        
        /// <remarks/>
        NotEqualBusinessId,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    public enum FilterTypes {
        
        /// <remarks/>
        @string,
        
        /// <remarks/>
        guid,
        
        /// <remarks/>
        @int,
        
        /// <remarks/>
        @bool,
        
        /// <remarks/>
        datetime,
        
        /// <remarks/>
        @null,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("not-null")]
        notnull,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class DataBlockExportSort {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Attribute;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(SortTypes.Asc)]
        public SortTypes Type;
        
        public DataBlockExportSort() {
            this.Type = SortTypes.Asc;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    public enum SortTypes {
        
        /// <remarks/>
        Asc,
        
        /// <remarks/>
        Desc,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class DataBlockExportAttribute {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Name;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool IncludeNull;
        
        public DataBlockExportAttribute() {
            this.IncludeNull = false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DataBlock {
        
        /// <remarks/>
        public DataBlockExport Export;
        
        /// <remarks/>
        public DataBlockImport Import;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Relation")]
        public DataBlockRelation[] Relation;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Name;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Entity;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public EntityTypes Type;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TypeSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string IntersectName;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class DataBlockRelation {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Block;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Attribute;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute("PK-Attribute")]
        public string PKAttribute;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool IncludeNull;
        
        public DataBlockRelation() {
            this.IncludeNull = false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    public enum EntityTypes {
        
        /// <remarks/>
        Entity,
        
        /// <remarks/>
        Intersect,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SolutionBlockImport {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Solution", IsNullable=false)]
        public SolutionBlockImportSolution[] PreRequisites;
        
        /// <remarks/>
        public Blocks PostSuccessfulImportBlocks;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(true)]
        public bool OverwriteSameVersion;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool OverwriteNewerVersion;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public SolutionTypes Type;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool ActivateServersideCode;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool OverwriteCustomizations;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool PublishAll;
        
        public SolutionBlockImport() {
            this.OverwriteSameVersion = true;
            this.OverwriteNewerVersion = false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class SolutionBlockImportSolution {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Name;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public SolutionVersionComparers Comparer;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Version;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    public enum SolutionVersionComparers {
        
        /// <remarks/>
        any,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("eq-this")]
        eqthis,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("ge-this")]
        gethis,
        
        /// <remarks/>
        eq,
        
        /// <remarks/>
        ge,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Blocks {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("DataBlock", typeof(DataBlock))]
        [System.Xml.Serialization.XmlElementAttribute("SolutionBlock", typeof(SolutionBlock))]
        public object[] Items;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SolutionBlock {
        
        /// <remarks/>
        public SolutionBlockExport Export;
        
        /// <remarks/>
        public SolutionBlockImport Import;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Name;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Path;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string File;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SolutionBlockExport {
        
        /// <remarks/>
        public SolutionBlockExportSettings Settings;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public SolutionTypes Type;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string SetVersion;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool PublishBeforeExport;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string TargetVersion;
        
        public SolutionBlockExport() {
            this.PublishBeforeExport = false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class SolutionBlockExportSettings {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool AutoNumbering;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool Calendar;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool Customization;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool EmailTracking;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool General;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool Marketing;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool OutlookSync;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool RelationshipRoles;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool IsvConfig;
        
        public SolutionBlockExportSettings() {
            this.AutoNumbering = false;
            this.Calendar = false;
            this.Customization = false;
            this.EmailTracking = false;
            this.General = false;
            this.Marketing = false;
            this.OutlookSync = false;
            this.RelationshipRoles = false;
            this.IsvConfig = false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    public enum SolutionTypes {
        
        /// <remarks/>
        Managed,
        
        /// <remarks/>
        Unmanaged,
        
        /// <remarks/>
        Both,
        
        /// <remarks/>
        None,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class ShuffleDefinition {
        
        /// <remarks/>
        public Blocks Blocks;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int Timeout;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TimeoutSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool StopOnError;
        
        public ShuffleDefinition() {
            this.StopOnError = false;
        }
    }
}
